apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobot-data-pvc
  namespace: jobot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: jobot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
